using System.Globalization;

namespace GtaSaModManager.Services;

public enum SupportedLanguage
{
    English,
    Persian
}

public class LocalizationService
{
    private static readonly Dictionary<string, string> EnglishStrings = new()
    {
        ["AppTitle"] = "GTA San Andreas Mod Manager",
        ["GameStatus"] = "Game Status",
        ["GamePath"] = "Game Path",
        ["GameFolderNotConfigured"] = "Game folder not configured",
        ["OpenGameFolder"] = "Open Game Folder",
        ["RunGame"] = "Run Game",
        ["WannaInstallMoreMods"] = "Wanna install more mods?",
        ["AssetAlreadyInstalledTitle"] = "Asset mod already installed",
        ["AssetAlreadyInstalledPrompt"] = "This package is already installed. Choose what to do with its model.",
        ["AssetModelAlreadyExists"] = "'{0}' already exists in this mod folder. Replace its model files?",
        ["AssetConflictTitle"] = "Possible mod conflict",
        ["AssetConflictWarning"] = "These models may conflict; only one copy of each may work in the game:\n{0}",
        ["AssetAlsoUsedBy"] = "'{0}' is also used by: {1}",
        ["InstallAnyway"] = "Install Anyway",
        ["ChooseAnother"] = "Choose Another",
        ["Delete"] = "Delete",
        ["DeleteSomeModels"] = "Delete Some Models",
        ["SelectModelsToDelete"] = "Select models to delete",
        ["DeleteSelectedModels"] = "Delete Selected",
        ["DeleteSelectedModelsSucceeded"] = "Selected models were deleted.",
        ["DeletingSelectedModels"] = "Deleting selected models",
        ["DeleteManifestUpdateFailed"] = "Could not update installation records for: {0}",
        ["DeleteAssetInstallationFailed"] = "Could not delete '{0}' from modloader.",
        ["Deleting"] = "Deleting",
        ["DeletingMod"] = "Deleting {0}",
        ["DeleteFileFailed"] = "Could not delete file: {0}",
        ["DeleteFolderFailed"] = "Could not delete folder: {0}",
        ["DeleteFolderReadFailed"] = "Could not read folder: {0}",
        ["DeleteProgressComplete"] = "Deletion complete.",
        ["DeleteProgressFailed"] = "Deletion failed.",
        ["ModDeletedTitle"] = "Mod deleted",
        ["ModDeletedDescription"] = "The mod and its files were deleted.",
        ["RenamePreviousModel"] = "Rename the Previous Model",
        ["KeepPreviousInstallAnotherModel"] = "Keep Previous & Install as Another Model",
        ["InstallMod"] = "Install Mod",
        ["Install"] = "Install",
        ["UninstallMod"] = "Uninstall Mod",
        ["UninstallCompleted"] = "The mod was uninstalled successfully.",
        ["UninstallModFailed"] = "The selected mod could not be uninstalled.",
        ["ModLoaderMods"] = "ModLoader Mods",
        ["ModLibraryTitle"] = "Mod Library",
        ["ModLibraryPath"] = "Base Mods Folder",
        ["Settings"] = "Settings",
        ["ModLibrary"] = "Mod Library",
        ["AvailableMods"] = "Available Mods",
        ["InstalledMods"] = "Installed Mods",
        ["Change"] = "Change",
        ["OpenFolder"] = "Open Folder",
        ["Browse"] = "Browse",
        ["Configured"] = "Configured",
        ["NotConfigured"] = "Not configured",
        ["NoModsInstalled"] = "No ModLoader mods installed yet.",
        ["NoModPackagesInLibrary"] = "No mod packages found in this library yet.",
        ["ViewReadme"] = "View README",
        ["GameFolderNotConfiguredMessage"] = "Please select a valid GTA San Andreas folder first.",
        ["SelectMod"] = "Select a mod folder or archive",
        ["ExtractionFailed"] = "The mod archive could not be extracted.",
        ["DuplicateModPrompt"] = "A mod named '{0}' already exists. Replace it?",
        ["Installing"] = "Installing",
        ["CheckingPreviousInstallation"] = "Checking previous installation",
        ["PreviousInstallationCheckFailed"] = "Could not check for a previous installation.",
        ["LoadingVehicles"] = "Loading vehicles...",
        ["LoadingSkins"] = "Loading skins...",
        ["LoadingWeapons"] = "Loading weapons...",
        ["LoadingAssets"] = "Loading...",
        ["LoadingAssets"] = "Loading...",
        ["InstallationCompleted"] = "Installation completed successfully.",
        ["InstallationFailed"] = "The mod could not be installed.",
        ["ModSourceInvalid"] = "The selected mod could not be read.",
        ["SelectGameFolder"] = "Select the GTA San Andreas folder",
        ["SelectModLibraryFolder"] = "Select the Mod Library / Mods Source Folder",
        ["InvalidGameFolder"] = "This folder does not contain gta_sa.exe.",
        ["InvalidModLibraryFolder"] = "This folder is not a valid mods library folder.",
        ["GameLaunchFailed"] = "The game could not be launched.",
        ["InstallingTitle"] = "Installing",
        ["Theme"] = "Theme",
        ["ThemeNameSystem"] = "System",
        ["ThemeNameLightBlue"] = "Light Blue",
        ["ThemeNameLightPurple"] = "Light Purple",
        ["ThemeNameLightGreen"] = "Light Green",
        ["ThemeNameLightOrange"] = "Light Orange",
        ["ThemeNameDarkBlue"] = "Dark Blue",
        ["ThemeNameDarkPurple"] = "Dark Purple",
        ["ThemeNameDarkGreen"] = "Dark Green",
        ["ThemeNameDarkRed"] = "Dark Red",
        ["Language"] = "Language",
        ["Installed"] = "Installed",
        ["Status"] = "Status",
        ["Step1GameFolder"] = "Game folder",
        ["Step2Profile"] = "Base Mods Folder",
        ["Step3Mod"] = "Select mod",
        ["Step4Installing"] = "Installing",
        ["Step5Category"] = "Cars / Weapons / Skins",
        ["Step6Completed"] = "Completed",
        ["GameFolderRequired"] = "Choose your GTA San Andreas folder.",
        ["ModFolder"] = "Mod Folder",
        ["BrowseModFolder"] = "Browse mod folder",
        ["DetectedMod"] = "Detected mod",
        ["DetectedModStatus"] = "Detected mod: {0} ✓",
        ["AssetStepTitleVehicle"] = "If you wish to select the Vehicle model to be replaced...",
        ["AssetStepTitleWeapon"] = "If you wish to select the Weapon model to be replaced...",
        ["AssetStepTitleSkin"] = "If you wish to select the Skin model to be replaced...",
        ["AssetStepTitleGeneric"] = "If you wish to select the model to be replaced...",
        ["AssetTypeVehicle"] = "Vehicle",
        ["AssetTypeSkin"] = "Skin",
        ["AssetTypeWeapon"] = "Weapon",
        ["AssetTypePromptTitle"] = "Select asset type",
        ["AssetTypePrompt"] = "The model '{0}' was not found. Select its asset type.",
        ["AssetCategory"] = "Category",
        ["AssetColumns"] = "Columns",
        ["AssetSort"] = "Sort",
        ["AssetUsedBy"] = "Used by: {0}",
        ["MultiModelStepTitle"] = "Model {0} of {1}: {2}",
        ["NextModel"] = "Next model ({0}/{1})",
        ["MultiAssetTargetAlreadyMapped"] = "This asset is already mapped to another model in this package. Choose a different asset.",
        ["KeepOriginalName"] = "Keep original name",
        ["SkipThisModel"] = "Skip this model",
        ["InstallRemainingOriginalNames"] = "Install the remaining {0} with original names",
        ["UnknownMultiAssetModel"] = "'{0}' is not in the asset catalog.",
        ["MultiAssetSummaryTitle"] = "Review model mappings",
        ["MultiAssetSummaryMapped"] = "Mapped: {0} -> {1}",
        ["MultiAssetSummaryKeep"] = "Keep: {0}",
        ["MultiAssetSummarySkipped"] = "Skipped: {0}",
        ["MultiAssetSummaryPending"] = "Unresolved: {0}",
        ["MultiAssetFilesLeftOut"] = "Files left out:",
        ["SortByFileName"] = "Sort by file name",
        ["SortById"] = "Sort by ID",
        ["AssetAll"] = "All",
        ["AssetNoMatching"] = "No matching assets were found in this Mod.",
        ["CategoryPlaceholder"] = "This category step is reserved for future advanced installers.",
        ["InstallationComplete"] = "Installation complete.",
        ["ReadMe"] = "Read Me",
        ["OpenReadmeFile"] = "Open README.txt",
        ["ReadmeFallback"] = "README",
        ["ImageNotValid"] = "IMAGE NOT VALID",
        ["ImageUnavailable"] = "No image available",
        ["ImageUnavailableFriendly"] = "No image available",
        ["BaseModsFolderTitle"] = "Base Mods Folder",
        ["BaseModsFolderSubtitle"] = "Select the base mod folder for easy access",
        ["Previous"] = "Previous",
        ["Next"] = "Next",
        ["ShowMore"] = "Show More",
        ["ShowLess"] = "Show Less",
        ["Close"] = "Close",
        ["Warning"] = "Warning",
        ["Error"] = "Error",
        ["Failed"] = "Failed",
        ["Cancel"] = "Cancel",
        ["Continue"] = "Continue",
        ["Back"] = "Back",
        ["Completed"] = "Completed",
        ["CompletedIn"] = "Completed in",
        ["SelectModFolder"] = "Select the mod folder",
        ["ModJsonInvalid"] = "The package manifest is malformed or contains unexpected content. The mod name still uses the folder name.",
        ["SelectModFirst"] = "Please select a valid mod folder first.",
        ["ModFolderEmpty"] = "The selected mod folder is empty or unreadable.",
        ["English"] = "English",
        ["Persian"] = "Persian"
    };

    private static readonly Dictionary<string, string> PersianStrings = new()
    {
        ["GamePath"] = "مسیر بازی",
        ["GameFolderNotConfigured"] = "پوشه بازی پیکربندی نشده است",
        ["OpenGameFolder"] = "باز کردن پوشه بازی",
        ["RunGame"] = "اجرای بازی",
        ["WannaInstallMoreMods"] = "میخواهی مد بیشتری نصب کنی ؟",
        ["AssetAlreadyInstalledTitle"] = "این مد قبلاً نصب شده است",
        ["AssetAlreadyInstalledPrompt"] = "این بسته قبلاً نصب شده است. برای مدل قبلی چه کاری انجام دهیم؟",
        ["AssetModelAlreadyExists"] = "مدل «{0}» از قبل در این پوشه وجود دارد. فایل‌های مدل آن جایگزین شود؟",
        ["AssetConflictTitle"] = "تداخل احتمالی مودها",
        ["AssetConflictWarning"] = "مدل‌های زیر ممکن است تداخل داشته باشند؛ ممکن است فقط یکی از هر مدل در بازی کار کند:\n{0}",
        ["AssetAlsoUsedBy"] = "«{0}» در این مودها هم استفاده شده است: {1}",
        ["InstallAnyway"] = "با این حال نصب کن",
        ["ChooseAnother"] = "انتخاب مدل دیگر",
        ["Delete"] = "حذف",
        ["DeleteSomeModels"] = "حذف برخی مدل‌ها",
        ["SelectModelsToDelete"] = "مدل‌های موردنظر برای حذف را انتخاب کنید",
        ["DeleteSelectedModels"] = "حذف انتخاب‌شده‌ها",
        ["DeleteSelectedModelsSucceeded"] = "مدل‌های انتخاب‌شده حذف شدند.",
        ["DeletingSelectedModels"] = "در حال حذف مدل‌های انتخاب‌شده",
        ["DeleteManifestUpdateFailed"] = "به‌روزرسانی سوابق نصب انجام نشد: {0}",
        ["DeleteAssetInstallationFailed"] = "حذف «{0}» از modloader انجام نشد.",
        ["Deleting"] = "در حال حذف",
        ["DeletingMod"] = "در حال حذف {0}",
        ["DeleteFileFailed"] = "حذف فایل انجام نشد: {0}",
        ["DeleteFolderFailed"] = "حذف پوشه انجام نشد: {0}",
        ["DeleteFolderReadFailed"] = "خواندن پوشه انجام نشد: {0}",
        ["DeleteProgressComplete"] = "حذف کامل شد.",
        ["DeleteProgressFailed"] = "حذف ناموفق بود.",
        ["ModDeletedTitle"] = "مود حذف شد",
        ["ModDeletedDescription"] = "مود و فایل‌های آن حذف شدند.",
        ["RenamePreviousModel"] = "مدل قبلی را حذف و مدل جدید را جایگزین کن",
        ["KeepPreviousInstallAnotherModel"] = "مدل قبلی را نگه دار و این مد را به‌عنوان مدل دیگری نصب کن",
        ["InstallMod"] = "نصب مود",
        ["Install"] = "نصب",
        ["UninstallMod"] = "حذف مود",
        ["UninstallCompleted"] = "مود با موفقیت حذف شد.",
        ["UninstallModFailed"] = "حذف مود انتخاب‌شده انجام نشد.",
        ["ModLoaderMods"] = "مودهای ModLoader",
        ["ModLibraryTitle"] = "کتابخانه مودها",
        ["ModLibraryPath"] = "پوشه مودها",
        ["Settings"] = "تنظیمات",
        ["ModLibrary"] = "کتابخانه مودها",
        ["AvailableMods"] = "مودهای موجود",
        ["InstalledMods"] = "مودهای نصب‌شده",
        ["Change"] = "تغییر",
        ["OpenFolder"] = "باز کردن پوشه",
        ["Browse"] = "انتخاب",
        ["Configured"] = "پیکربندی شد",
        ["NotConfigured"] = "پیکربندی نشده",
        ["NoModsInstalled"] = "هنوز هیچ مود ModLoader نصب نشده است.",
        ["NoModPackagesInLibrary"] = "هنوز هیچ بسته مودی در این کتابخانه وجود ندارد.",
        ["ViewReadme"] = "نمایش README",
        ["GameFolderNotConfiguredMessage"] = "لطفاً ابتدا یک پوشه معتبر برای GTA San Andreas انتخاب کنید.",
        ["SelectMod"] = "یک پوشه یا آرشیو مود انتخاب کنید",
        ["ExtractionFailed"] = "آرشیو مود را نمی‌توان استخراج کرد.",
        ["DuplicateModPrompt"] = "مدی با نام '{0}' از قبل وجود دارد. جایگزین شود؟",
        ["Installing"] = "در حال نصب",
        ["CheckingPreviousInstallation"] = "در حال بررسی نصب قبلی",
        ["PreviousInstallationCheckFailed"] = "بررسی نصب قبلی انجام نشد.",
        ["LoadingVehicles"] = "در حال بارگذاری وسیله‌های نقلیه...",
        ["LoadingSkins"] = "در حال بارگذاری اسکین‌ها...",
        ["LoadingWeapons"] = "در حال بارگذاری اسلحه‌ها...",
        ["LoadingAssets"] = "در حال لود ...",
        ["LoadingAssets"] = "در حال لود ...",
        ["InstallationCompleted"] = "نصب با موفقیت انجام شد.",
        ["InstallationFailed"] = "نصب مود انجام نشد.",
        ["ModSourceInvalid"] = "مود انتخاب‌شده قابل خواندن نبود.",
        ["SelectGameFolder"] = "پوشه GTA San Andreas را انتخاب کنید",
        ["SelectModLibraryFolder"] = "پوشه کتابخانه مودها / منبع مودها را انتخاب کنید",
        ["InvalidGameFolder"] = "این پوشه شامل gta_sa.exe نمی‌شود.",
        ["InvalidModLibraryFolder"] = "این پوشه یک کتابخانه معتبر برای مودها نیست.",
        ["GameLaunchFailed"] = "اجرای بازی انجام نشد.",
        ["InstallingTitle"] = "در حال نصب",
        ["Theme"] = "تم",
        ["ThemeNameSystem"] = "سیستم",
        ["ThemeNameLightBlue"] = "آبی روشن",
        ["ThemeNameLightPurple"] = "بنفش روشن",
        ["ThemeNameLightGreen"] = "سبز روشن",
        ["ThemeNameLightOrange"] = "نارنجی روشن",
        ["ThemeNameDarkBlue"] = "آبی تیره",
        ["ThemeNameDarkPurple"] = "بنفش تیره",
        ["ThemeNameDarkGreen"] = "سبز تیره",
        ["ThemeNameDarkRed"] = "قرمز تیره",
        ["Language"] = "زبان",
        ["Installed"] = "نصب شده",
        ["Status"] = "وضعیت",
        ["Step1GameFolder"] = "پوشه بازی",
        ["Step2Profile"] = "پروفایل بازی",
        ["Step3Mod"] = "انتخاب مود",
        ["Step4Installing"] = "در حال نصب",
        ["Step5Category"] = "ماشین / اسلحه / اسکین",
        ["Step6Completed"] = "تکمیل شد",
        ["GameFolderRequired"] = "پوشه GTA San Andreas خود را انتخاب کنید.",
        ["ModFolder"] = "پوشه مود",
        ["BrowseModFolder"] = "انتخاب پوشه مود",
        ["DetectedMod"] = "مود تشخیص داده شد",
        ["DetectedModStatus"] = "مود تشخیص داده شد: {0} ✓",
        ["AssetStepTitleVehicle"] = "اگر می‌خواهید مدل وسیله نقلیه جایگزین‌شده را انتخاب کنید...",
        ["AssetStepTitleWeapon"] = "اگر می‌خواهید مدل اسلحه جایگزین‌شده را انتخاب کنید...",
        ["AssetStepTitleSkin"] = "اگر می‌خواهید مدل شخصیت جایگزین‌شده را انتخاب کنید...",
        ["AssetStepTitleGeneric"] = "اگر می‌خواهید مدل جایگزین‌شده را انتخاب کنید...",
        ["AssetTypeVehicle"] = "وسیله نقلیه",
        ["AssetTypeSkin"] = "شخصیت",
        ["AssetTypeWeapon"] = "اسلحه",
        ["AssetTypePromptTitle"] = "نوع مدل را انتخاب کنید",
        ["AssetTypePrompt"] = "مدل «{0}» در فهرست شناخته‌شده‌ها نیست. نوع آن را انتخاب کنید.",
        ["AssetCategory"] = "دسته‌بندی",
        ["AssetColumns"] = "ستون‌ها",
        ["AssetSort"] = "مرتب‌سازی",
        ["AssetUsedBy"] = "استفاده‌شده در: {0}",
        ["MultiModelStepTitle"] = "مدل {0} از {1}: {2}",
        ["NextModel"] = "مدل بعدی ({0}/{1})",
        ["MultiAssetTargetAlreadyMapped"] = "این مدل قبلاً به مدل دیگری در این بسته اختصاص داده شده است. مدل دیگری انتخاب کنید.",
        ["KeepOriginalName"] = "حفظ نام اصلی",
        ["SkipThisModel"] = "رد کردن این مدل",
        ["InstallRemainingOriginalNames"] = "نصب {0} مدل باقی‌مانده با نام اصلی",
        ["UnknownMultiAssetModel"] = "«{0}» در فهرست مدل‌ها نیست.",
        ["MultiAssetSummaryTitle"] = "بررسی نگاشت مدل‌ها",
        ["MultiAssetSummaryMapped"] = "نگاشت‌شده: {0} ← {1}",
        ["MultiAssetSummaryKeep"] = "حفظ نام اصلی: {0}",
        ["MultiAssetSummarySkipped"] = "ردشده: {0}",
        ["MultiAssetSummaryPending"] = "تعیین‌نشده: {0}",
        ["MultiAssetFilesLeftOut"] = "فایل‌های کنارگذاشته‌شده:",
        ["SortByFileName"] = "بر اساس نام فایل",
        ["SortById"] = "بر اساس شناسه",
        ["AssetAll"] = "همه",
        ["AssetNoMatching"] = "هیچ مورد منطبقی برای این مود پیدا نشد.",
        ["CategoryPlaceholder"] = "این مرحله برای نصب‌کننده‌های پیشرفته آینده رزرو شده است.",
        ["InstallationComplete"] = "نصب کامل شد.",
        ["ReadMe"] = "خواندن راهنما",
        ["OpenReadmeFile"] = "باز کردن README.txt",
        ["ReadmeFallback"] = "README",
        ["ImageNotValid"] = "تصویر نامعتبر",
        ["ImageUnavailable"] = "تصویر موجود نیست",
        ["ImageUnavailableFriendly"] = "تصویر موجود نیست",
        ["BaseModsFolderTitle"] = "پوشه پایه مودها",
        ["BaseModsFolderSubtitle"] = "پوشه پایه مود را برای دسترسی سریع انتخاب کنید",
        ["Previous"] = "قبلی",
        ["Next"] = "بعدی",
        ["ShowMore"] = "نمایش بیشتر",
        ["ShowLess"] = "نمایش کمتر",
        ["Close"] = "بستن",
        ["Warning"] = "هشدار",
        ["Error"] = "خطا",
        ["Failed"] = "ناموفق",
        ["Cancel"] = "لغو",
        ["Continue"] = "ادامه",
        ["Back"] = "بازگشت",
        ["Completed"] = "تکمیل شد",
        ["CompletedIn"] = "تکمیل شد در",
        ["SelectModFolder"] = "پوشه مود را انتخاب کنید",
        ["ModJsonInvalid"] = "مانیفست بسته نامعتبر است یا محتوای غیرمنتظره دارد. نام مود همچنان از نام پوشه گرفته می‌شود.",
        ["SelectModFirst"] = "لطفاً ابتدا یک پوشه مود معتبر انتخاب کنید.",
        ["ModFolderEmpty"] = "پوشه مود انتخاب‌شده خالی یا غیرقابل خواندن است.",
        ["English"] = "English",
        ["Persian"] = "فارسی"
    };

    public string GetString(string key, string fallback = "")
    {
        var currentLanguage = ParseLanguage(CultureInfo.CurrentUICulture.Name);
        return GetStringForLanguage(key, currentLanguage, fallback);
    }

    public string GetStringForLanguage(string key, string language, string fallback = "")
    {
        return GetStringForLanguage(key, ParseLanguage(language), fallback);
    }

    private static string GetStringForLanguage(string key, SupportedLanguage language, string fallback)
    {
        var dictionary = language == SupportedLanguage.Persian ? PersianStrings : EnglishStrings;
        return dictionary.TryGetValue(key, out var value) && !string.IsNullOrWhiteSpace(value) ? value : fallback;
    }

    public string Get(string key, string fallback = "") => GetString(key, fallback);

    public SupportedLanguage ParseLanguage(string? value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return SupportedLanguage.English;
        }

        if (value.StartsWith("fa", StringComparison.OrdinalIgnoreCase) ||
            string.Equals(value, SupportedLanguage.Persian.ToString(), StringComparison.OrdinalIgnoreCase))
        {
            return SupportedLanguage.Persian;
        }

        return SupportedLanguage.English;
    }

    public CultureInfo GetCultureForLanguage(string language)
    {
        return ParseLanguage(language) switch
        {
            SupportedLanguage.Persian => new CultureInfo("fa-IR"),
            _ => new CultureInfo("en-US")
        };
    }
}
